# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#

# Title and description of your site
title:        'Frank Ganske at GitHub'
description:  'Redirect to Mo Cuishle...'
author:       'Frank Ganske'
author.uri:   'https://github.com/ganskef'

gems:
    - jekyll-gist
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-redirect-from

# Build settings
url:          'https://ganskef.github.io/'
baseurl:      ''
urlimg:       'https://ganskef.github.io/images/'
markdown:     kramdown
highlighter:  rouge
permalink:    /
encoding:     utf-8
timezone:     Europe/Berlin
future:       true

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md
